### PR TITLE
Fix custom Host header with arbitrary case

### PR DESCRIPTION
**Pull request by TimothyGu**
Regression since 1592ca1148e657110fd6f64dc8b29a576cd1da1c.

Fixes: #416
Fixes: #425

### CODE REVIEW

**Comment by bitinn** [comment]
Interesting so the header keeps its original value and request get the right host string.

But you might add a line in test to verify the original `hoSt` header name is not changed? That's what you are trying to preserve, right?

**Comment by TimothyGu** [comment]
> But you might add a line in test to verify the original `hoSt` header name is not changed? That's what you are trying to preserve, right?

Yes, but we can't actually test for that since Node.js force-lowercases everything on the server side.

**Comment by bitinn** [comment]
But we could check the *request* headers, no? It's not affected by node.js http module, right?

**Comment by TimothyGu** [comment]
@bitinn But we can't get access to the request object given the current API surface, unless you meant check `exportNodeCompatibleHeaders` directly?

**Pull request merged**
