### PR TITLE
Revert "Return empty .json() object on 204. Fix #165. (#166)"

### LINKED ISSUE #165: Return empty object on 204 No Content...
...instead of throwing a syntax error due to attempting to JSON parse `''`.

```
let fetch = require('node-fetch');
fetch('http://httpbin.org/status/204').then(res => res.json()).then(object => {
    console.log(object);
}).catch(error => console.error(error));
```

Demo: http://runkit.com/dandv/node-fetch-204-no-content

Fixing this would attain compatibility with [request](https://github.com/request/request/issues/2177) and [got](https://github.com/sindresorhus/got/pull/78).

More generally, it would be more tolerant to return an empty object if the response is the empty string (regardless of the status code being 204 or other 2xx).

### PR DESCRIPTION
**Pull request by TimothyGu**
This reverts commit 95b58936b8673f7fdc21050c3bfeb460e9b00bf1.

Fixes #165.

### CODE REVIEW

**Comment by hmarr** [comment]
Hello! Any chance this could be back-ported to a 1.x.x release? Not throwing the error broke compatibility with browser fetch implementations, so I'd consider this commit a fix that gets us back to the previous desired behaviour.

Thanks!

**Comment by bitinn** [comment]
It's been a while since I looked at 1.x release, if it's indeed affected I can take a PR to fix it.

PS: 2.x should be ready for use if you want to. We don't intend to backport spec related changes to 1.x if possible (as 2.x is intended to address this issue without raising too much upgrade problems).

(From my phone)

**Comment by hmarr** [comment]
Ok, thanks @bitinn. What's the ETA for a 2.0 final release?

I'm using node-fetch via [fetch-mock](https://github.com/wheresrhys/fetch-mock), which [depends on 1.x](https://github.com/wheresrhys/fetch-mock/blob/ecac8c5e8e888a8148b5f84ac07bd349708bed59/package.json#L33), and I imagine they'd want to wait for a non-prerelease of v2 before upgrading.

If it's going to be a while off, I'll put in a PR for 1.x doing the backport.

**Comment by bitinn** [comment]
@hmarr actually I have already fixed it in recent v1.7.0 release :)

**Comment by hmarr** [comment]
@bitinn brilliant, thanks!

**Pull request merged**
