### PR TITLE
Convert Headers to ES2015 and implement Iterable interface

### LINKED ISSUE #127: Incompatible API in Headers class
Hi,

I use [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) in my project with [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch). Unfortunately there are some incompatibilities between [Headers API](https://developer.mozilla.org/en-US/docs/Web/API/Headers) and https://github.com/bitinn/node-fetch/blob/master/lib/headers.js.

Missing methods:
- entries
- keys
- values

### PR DESCRIPTION
**Pull request by TimothyGu**
Closes #127, #174.

The approach taken by this pull request versus #174 is that the iterator methods are greatly simplified as well as more correct w.r.t. the behavior of `keys()` in case of multiple values.

### CODE REVIEW

**Comment by jimmywarting** [comment]
Another tip would just be to include https://www.npmjs.com/package/fetch-headers as a dependency

**Comment by TimothyGu** [comment]
@jimmywarting, in general I don't see why we need to add a dependency when we could just copy that into this repo.

W.r.t. the code, we still maintain compatibility with Node.js versions as old as 0.10, which your package doesn't seem to do. I'm also not sure about why you used WeakMap.

W.r.t. the additional checks of `normalizeName` and `normalizeValue`, I will add them in a future pull request. There are certain API differences between GitHub's Fetch and the Fetch Standard that we need to discuss, before proceeding with changing it.

W.r.t. `Symbol.toStringTag`, good suggestion. I've incorporated that in this PR as well.

**Comment by jimmywarting** [comment]
I just think it's a good idea to factor out some of the logic so it can be used by others as well.
dose keeping this package smaller and cleaner

WeakMap is 100% private and Symbol('map') isn't since you can always get the reference.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols

**Comment by jimmywarting** [comment]
node v0.10 don't support class so...?

**Comment by TimothyGu** [comment]
We compile the sources with Babel now.

Okay, so WeakMap is in reality more private than Symbols, but with Symbols you also get the advantage of being able to introspect the underlying data structure. So it's like "whatever you want to do you can't touch the map" versus "we've warned you that this object is internal, but if you _really really want_ to see what's in there you can, just don't overdo it." I think I prefer the latter's flexibility.

Symbols are also the approach used by some other projects like Babel.

**Comment by jimmywarting** [comment]
Sure, if we use babel then i don't see any problem with my lib being included in the build process

**Comment by TimothyGu** [comment]
Also CC @soyuka.

**Comment by bitinn** [comment]
@TimothyGu Just a quick remainder: while code coverage remains 100%, maybe it's worth double-checking if all newly added features are tested.

Also a good practice: keep each test short and concise if possible, I haven't read the test throughly, maybe it can be refactored somehow. It's more verbose for sure, but in testing it maybe better to have multiple small tests for each edge cases/features instead of a large one.

**Pull request merged**
