### PR TITLE
Add "response.redirected" property support

### PR DESCRIPTION
**Pull request by 410stats**
As described in https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected
If any redirection happened, it will be equal to true. Otherwise it will be equal to false.

There is two basic test is the commit to cover this property.

### CODE REVIEW

**Comment by jimmywarting** [comment]
Mistakenly thought this to solve my recently added issue #517  😜

**Comment by bitinn** [comment]
I think this is largely fine to end users, though it seems the spec has changed quite a lot, there is a URL List now which `redirected` getter is required to check. 

https://fetch.spec.whatwg.org/#concept-response-url-list
https://fetch.spec.whatwg.org/#dom-response-redirected

**Comment by 410stats** [comment]
> I think this is largely fine to end users, though it seems the spec has changed quite a lot, there is a URL List now which `redirected` getter is required to check.
> 
> https://fetch.spec.whatwg.org/#concept-response-url-list
> https://fetch.spec.whatwg.org/#dom-response-redirected

Thanks for the link !
To follow the specs, we should have in Response object an internal array containing URL of previous redirection (if i understood correctly, as i cannot find an example of implementation...).
It should be used also for the Response.url method that need to return the last element of this array.

So it's really doable, but this implies more internal modifications and thus more testing than this little commit. And Response.redirected is the only way to know that a redirection happened without handling redirection manually ...
For the moment i think we should push this and modify methods in a later commit when the internal URL list will be added to respect the specs 👍

**Comment by jimmywarting** [comment]
Just needed this feature atm.

**Comment by bitinn** [comment]
sorry for the late update, this is now available in v2.5.0, thx @410stats !

**Pull request closed without merging**
