### PR TITLE
add timings

### LINKED ISSUE #363: Add timings for http calls
Would be good to expose timings of http calls for things like dns lookups and so on without introducing a shim to achieve this.

E.g 
https://blog.risingstack.com/measuring-http-timings-node-js/

https://github.com/RisingStack/opentracing-auto/blob/master/src/instrumentation/httpClient.js

### PR DESCRIPTION
**Pull request by ajohnstone**
fixes #363

### CODE REVIEW

**Comment by bitinn** [comment]
I am not against it per se but we try very hard to avoid extending Fetch Spec too much. I would keep it open for future discussion.

**Comment by ajohnstone** [comment]
@bitinn Not sure I follow your reservations, and how to proceed?

**Comment by bitinn** [comment]
@ajohnstone I believe timing data should be completely optional to users. And #284 is discussing some possible options to debug requests.

I believe `request` approach of accepting every features are wrong, so we usually stick with Fetch Spec. And it certainly doesn't expose this information through API.

@TimothyGu might have a different opinion but mine are not merging.

**Comment by ajohnstone** [comment]
Would be happy if req/res was exposed :+1:

**Comment by TimothyGu** [comment]
I agree with @bitinn on this.

**Comment by lostthetrail** [comment]
@TimothyGu @bitinn How about @ajohnstone suggestion of exposing the raw Node req/res objects, so that users can extend the module with the timing information we want/need?

**Comment by bitinn** [comment]
I agree that we need to get a move on at #284, but I am fully occupied with other projects, so unlikely the PR would come from me :(

Of course if anyone want to tackle #229, which discusses a more elegant way to do this, I am all ears.

**Comment by TimothyGu** [comment]
No movement on this; closing.

> How about @ajohnstone suggestion of exposing the raw Node req/res objects, so that users can extend the module with the timing information we want/need?

I'm fine with this.

**Pull request closed without merging**
