### PR TITLE
Include system error in FetchError if one occurs

### LINKED ISSUE #639: Provide more info about system error causes in FetchError
We are wrapping FetchErrors in our own errors and it would be nice to get more info about the causes of the error.

It would be nice if the systemError was saved in the FetchError when one is available. For our use-case the syscall of the systemError would be enough.

I can create a pr if this is approved.

### PR DESCRIPTION
**Pull request by aeb-sia**
Fixes #639

### CODE REVIEW

**Comment by aeb-sia** [comment]
@bitinn is there anything holding this back? It's not breaking just adding a little functionality

**Comment by bitinn** [comment]
Apologies as I have not had time to review and add this to v2 (I have been pausing v2 releases).

I will let others decide to rebase or rework FetchError in v3, which I believe some changes are coming.

cc @xxczaki

(From my phone)

**Comment by aeb-sia** [comment]
The failure is also present in the 3.x branch and I couldn't find an apparent cause. It's defintely not related to the change of this pr

**Comment by simhnna** [comment]
May I suggest an editorconfig file so the IDEs know how to format the code automatically?

**Comment by xxczaki** [comment]
@aeb-sia Thanks for your contribution!

@simhnna Sure, please create a new PR and make sure the base branch is `3.x` :smile:

**Comment by Richienb** [comment]
@xxczaki I've already created the editorconfig file. Check out the 3.x branch.

**Pull request merged**
