### PR TITLE
[WIP] Update dependencies

### PR DESCRIPTION
**Pull request by gr2m**
Follow up https://github.com/bitinn/node-fetch/issues/626#issuecomment-493311447

The tests are passing, but the build fails. I don’t use babel or rollup myself, any idea what the error could mean?

```
$ npm run build

> node-fetch@2.6.0 build /node-fetch
> cross-env BABEL_ENV=rollup rollup -c


src/index.js → lib/index.js, lib/index.es.js, lib/index.mjs...
[object Object]
    at Object.isRestProperty (/node-fetch/node_modules/@babel/types/lib/validators/generated/index.js:4288:11)
    at DestructuringTransformer.pushObjectPattern (/node-fetch/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:197:15)
    at DestructuringTransformer.push (/node-fetch/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:108:14)
    at DestructuringTransformer.init (/node-fetch/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:317:12)
    at PluginPass.VariableDeclaration (/node-fetch/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:468:27)
    at newFn (/node-fetch/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/node-fetch/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/node-fetch/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/node-fetch/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/node-fetch/node_modules/@babel/traverse/lib/context.js:118:16)

# ... more of the same

(!) Plugin at position 2 plugin: The transformBundle hook used by plugin at position 2 is deprecated. The renderChunk hook should be used instead.
created lib/index.js, lib/index.es.js, lib/index.mjs in 1.2s
```

### CODE REVIEW

**Comment by bitinn** [comment]
No idea yet, haven't used `babel` lately.

People in the know, feel free to suggest a fix.

**Comment by dmitriz** [comment]
@bitinn
> No idea yet, haven't used babel lately.
People in the know, feel free to suggest a fix.

It seems like using `babel` is holding up the development
with people less likely to contribute
which is especially concerning in view of 
https://github.com/bitinn/node-fetch/issues/567

My question -- is there any tangible benefit here to use `babel`,
strong enough to compensate for the added complexity?

From looking over the code, I can only see it for the ES6 imports.
Replacing those with CommonJS would seemingly eliminate the need to use `babel`.
This is not to debate general benefits of the ES6 imports,
rather the more practical question - to what extent these really matter for this project?

**Comment by bitinn** [comment]
#643 I plan to drop it or update it, but have no time to investigate this issue yet.

**Comment by Richienb** [comment]
During the development of 3.x, we've updated all the dependencies, primarily in https://github.com/bitinn/node-fetch/commit/155ef268ec59e0e18b626a13cc3151e2111cc4e4.

**Pull request closed without merging**
