### PR TITLE
add data uri support

### PR DESCRIPTION
**Pull request by caub**
Just proposing this, to behave like browsers fetch which can accept a data uri

not finished, but I don't have precise ideas on how to do

### CODE REVIEW

**Comment by TimothyGu** [comment]
`data` URLs are a can of worms as they are [notoriously underspecified](https://simonsapin.github.io/data-urls/). I would prefer to use an established parser on npm or something instead of rolling our own. https://www.npmjs.com/package/data-uri-to-buffer looks pretty nice.

Besides that, you have to construct a Response object, and return a promise from `fetch` that will resolve to that.

You also have to pass the `type` along to the Response object as a `Content-Type` header [per spec](https://fetch.spec.whatwg.org/#concept-scheme-fetch).

Handling non-`base64` URLs is needed too. See https://tools.ietf.org/html/rfc2397#section-2 on the format for `data` URLs in general, though data-uri-to-buffer will do this for you.

**Comment by TimothyGu** [comment]
Oh, and you need to be careful to wrap all the errors that may occur in the URL-to-data process in a promise instead of throwing synchronously in `fetch()`.

**Comment by caub** [comment]
Ok, great, thanks, will do, I'll try to behave like spec/browser

**Comment by caub** [comment]
normally it's ok now

**Comment by caub** [comment]
I know it's not very beautiful, but is it ok now?

**Comment by TimothyGu** [comment]
I'd like to put this on hold because of https://github.com/whatwg/fetch/pull/579.

**Comment by TimothyGu** [comment]
Looks like the standard change has landed. @caub, can you update this module to use https://www.npmjs.com/package/data-urls instead?

**Comment by caub** [comment]
@TimothyGu yup, done

**Comment by bitinn** [comment]
Is `data-urls` now a dependency instead of devDependency?

**Comment by caub** [comment]
it fails on node4 because `data-urls` contains some destructuring https://github.com/jsdom/data-urls/blob/master/lib/parser.js#L3

might add rollup there so

**Pull request closed without merging**
