### PR TITLE
Expose Blob

### PR DESCRIPTION
**Pull request by Errorname**
It would be useful to access the Blob polyfill you use.
This would allow us to manually create Blobs to pass to fetch.

### CODE REVIEW

**Comment by bitinn** [comment]
our Blob implementation is now published as a separate package, we will integration it to node-fetch in future release.

https://github.com/bitinn/fetch-blob

**Comment by jimmywarting** [comment]
What when through your mind when you decided to call it `fetch-blob` and not something like `node-blob`? 😂

Anyway, how would you get a blob then?

```js
fetch.blob = require(blob)

// or 
var impl = require(blob)
var res = await fetch(url) 
await res.blob(impl) 
```

or dose node-fetch rely on fetch-blob?

**Comment by bitinn** [comment]
node-blob already exists, don’t want to use named scope.

Probably want to go with a plug-in / mixin route, as it is a part of Timothy’s old goal. I haven’t decided yet.

(From my phone)

**Comment by jimmywarting** [comment]
ok, only the feature will tell

**Pull request closed without merging**
