### PR TITLE
Add code to support TLS client certificates in 1.x branch; bump to v1.7.4

### PR DESCRIPTION
**Pull request by ateamlunchbox**
I need to be able to include TLS info with the request, so added a few lines to copy the info from the init object into the Request when it is created.

### CODE REVIEW

**Comment by ateamlunchbox** [comment]
Investigating why tests failed now.

**Comment by ateamlunchbox** [comment]
Apologies as I'm new to node.  Fixing the failing test now.

**Comment by jimmywarting** [comment]
this not something achievable with a custom Agent?

**Comment by ateamlunchbox** [comment]
I am using [apollo-link-http](https://www.npmjs.com/package/apollo-link-http), and that uses node-fetch < 2.0.  I passed my client key/cert and custom CA cert in to apollo-link-http as TLS configuration options as part of the config for fetch, but the TLS info wasn't being copied down into the Request object.  I updated the code so that if TLS configuration information is defined in the initializing object, it will be copied into the new Request being created.

Again, I'm new to node, so if there is a different way of accomplishing my goal without updating this library I would love to entertain any suggestions.

**Comment by bitinn** [comment]
@ateamlunchbox I haven't used `apollo-link-http`, but are you saying somehow when you pass a `agent` to `createHttpLink`, it's not passing all options?

Ref:
- https://github.com/bitinn/node-fetch/pull/564
- https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/README.md

AFAIK, you shouldn't have any problem doing that with node-fetch 1.x directly, so it's likely something `apollo-link-http` can change?

**Pull request closed without merging**
