### PR TITLE
Implement request redirect modes

### PR DESCRIPTION
**Pull request by rricard**
Hi !

I implemented one missing piece of the spec that I need to see working about redirects.

Related spec part: https://fetch.spec.whatwg.org/\#concept-request-redirect-mode

### CODE REVIEW

**Comment by rricard** [comment]
Added tests, waiting for the CI...

**Comment by bitinn** [comment]
Thx for the PR, care to show me why this is important for your case?

I don't really see a good use case for this when we can already set `follow: 0` to disable following redirect?

**Comment by rricard** [comment]
I need to use it in tests in order to make assertions on the `location` or `set-cookie` headers without following it. If I use `follow: 0` I'll trigger an error without being able to access the response object (in which there are things I want to assert on). Moreover, that's in the spec. If you need me to refactor stuff or anything, I would be happy to do it!

**Comment by rricard** [comment]
Just read #8 and saw the security issues related to this https://fetch.spec.whatwg.org/#atomic-http-redirect-handling. That's true that in the spec https://fetch.spec.whatwg.org/#requestredirect, `manual` cannot be set but we're on node and that's something we could bypass ... And that's really important for those who were using something like [supertest](https://www.npmjs.com/package/supertest) before for testing API endpoints.

**Comment by bitinn** [comment]
Hmm, that's quite an edge case for using Fetch API, maybe if we have a better Error standard, we can expose headers/body of the failed response.

But for now, I would consider promisify a low-level API like `http.request` to achieve this particular need, because what you want is probably a request that don't follow by itself and give you full response? like doing a `curl -I http://some.redirect.url/` ?

By adding this optional flag, we are essentially saying: *don't reject when max redirect limit is reached, just get back the final response*. While I am ok not implementing some aspect of Fetch Spec security, accept a response when it should have rejected them, is really what hold me from moving in this direction.

**Comment by rricard** [comment]
The manual mode just stops there even if there's a redirection. It's not an error case, it's what we expect. A 302 is not an error, it's just a valid HTTP response and we should be able to inspect this response, at least in a server environment. In a client environment, sure, there are some security issues (you don't want to see a malicious script inspect a set-cookie header). In my opinion, fetch is a low level api (with promises), it should be able to handle this kind of thing (make an http request and stop there, don't follow anything).

I already promisified things like supertest. It works but it's not the fetch API: fetch is way nicer to use and way more flexible ...

**Comment by bitinn** [comment]
In both Fetch and XMLHttpRequest's view, redirect is explicitly transparent, even for `HEAD` request, so either you got to a page that isn't redirecting (Fulfilled, even for 4xx and 5xx), or you have reached the redirect limit or timeout or network error (which are all Rejected).

Allowing Fetch to stop at redirection would be an extension to that mental model (3xx can be Fulfilled or Rejected based your input). And we will have to answer questions like:

- Can I extract headers and body for each redirection if we follow more than once?
- Can we change the request headers and body upon redirection?

To me both answers would be No, and that's why I don't believe Fetch API is low-level in our context: because a truly low-level tool don't care about Promise or Status Code or JSON Parsing.

If you prefer a higher-level tool then `http(s).request`, maybe module like https://github.com/leukhin/co-request can help.

**Comment by bitinn** [comment]
After giving this more thought...

I would prefer an approach where rejected Error object contains optional `err.headers` and `err.body` of last response received (for cases like: `req.follow` is 0, but server response is a redirection). So user may do a `.catch` to inspect headers if so desired.

Having a standardized Error might also help debugging in general, we will collect feedbacks on #8 

Closing this PR, but thx for your input.

**Comment by rricard** [comment]
Ok, that's a perfectly reasonable approach. I'll work on it then. Thanks for your insightful feedback :)

**Pull request closed without merging**
