### PR TITLE
Adding Brotli Support

### PR DESCRIPTION
**Pull request by hlthi**
[Native support](https://github.com/nodejs/node/pull/24938)
[Node Documentation](https://nodejs.org/api/zlib.html#zlib_class_zlib_brotlidecompress)

### CODE REVIEW

**Comment by bitinn** [comment]
Thx for the PR, I will into merging it.

Just one request: could you change the tests to use `skip` instead of faking a pass by fallback to `gzip`?

**Comment by hlthi** [comment]
Seems like "should ignore invalid headers" test gone wrong in Node 12 @bitinn . 

- gzip/skip Request has been completed.

**Comment by bitinn** [comment]
@hlthi I suspect node 12 has changed how they handle invalid headers, so this test now fails on `test/server.js`, do you have node 12 installed, can you verify the issue exists on your local machine?

The PR itself looks good, but I will need to fix the node 12 issue first.

**Comment by hlthi** [comment]
Posssible problems

1.  [Switch default parser to llhttp] (https://github.com/nodejs/node/pull/24870)
    Maybe new http parser dont know what to do invalid characters :(

2. [HTTP2 doesnt support invalid header](https://nodejs.org/api/http2.html#http2_invalid_character_handling_in_header_names_and_values)

`
Header field-names must only contain one or more of the following ASCII characters: a-z, A-Z, 0-9, !, #, $, %, &, ', *, +, -, ., ^, _, ` (backtick), |, and ~.
`
But it isn't http2.


# Debug err
`
{
  "bytesParsed": 171,
  "code": "HPE_INVALID_HEADER_TOKEN",
  "reason": "Invalid header value char"
}
`

Investigate in LLHTTP

https://github.com/nodejs/llhttp/blob/7596c6456d38bfa8a60fddddf162212527462b45/src/llhttp/http.ts#L494-L499

LLHTTP waiting \r and \n ; but show \x07 and boom.

@bitinn

**Comment by bitinn** [comment]
thx for the PR, released as 2.4.0

**Pull request merged**
