### PR TITLE
add handle error of response body

### PR DESCRIPTION
**Pull request by dsuket**

### CODE REVIEW

**Comment by bitinn** [comment]
Thx for the PR, could you explain to me how do you run into a scenario where the body stream throws error, and what would happen at that point?

Better yet, can you think of a test case for this error handler?

**Comment by dsuket** [comment]
In some pages, despite Content-Encoding is specified to deflate, in fact also be transferred without being compressed.
At that time, an error occurres in the pipe processing of body, it can not handle the error.
There is a possibility that an error occurs when you expand the compression, so I think it is better that it was possible to handle the error of body .
It will show the example below.

```javascript
var fetch = require('node-fetch');
fetch('http://goo.gl/fb/').then(function(res) {
  return res.text();
}).then(function(text) {
  console.log(text);
}).catch(function(err) {
  console.log('err:', err);
});
```

**Comment by bitinn** [comment]
Thx, I will look into it soon.

**Comment by bitinn** [comment]
This is fixed in v1.3.3 release, which would reject body with incorrect content-encoding with a custom error message for easier debugging.

**Pull request closed without merging**
