### PR TITLE
Switch to inflateRaw when inflate header check fails

### PR DESCRIPTION
**Pull request by gzzhanghao**
See [chromium/filter/gzip_filter.cc:131](https://chromium.googlesource.com/chromium/src/net/+/master/filter/gzip_filter.cc#131)

> As noted in Mozilla implementation, some servers such as Apache with mod_deflate don't generate zlib headers.
> See 677409 for instances where this work around is needed.
> Insert a dummy zlib header and try again.

Possible fix for #93 and #45

### CODE REVIEW

**Comment by bitinn** [comment]
Thx for the PR and an explanation to the mystery!

But this is my opinion:

- I really don't feel well workaround server problem.
- IF we must do so, it should be supported through a well-tested small npm module (is there already one?), we certainly don't want to maintain this ourselves.

**Comment by bitinn** [comment]
On a second thought, why can't we detect zlib deflate from zlib deflateRaw? if we can, we only need to choose zlib inflate and inflateRaw and not add many lines of code.

**Comment by bitinn** [comment]
Actually, if we want to be rough about this, try `zlib.inflate` and catch any error with `zlib.inflateRaw`, if none works, throw a custom error to inform users.

**Comment by gzzhanghao** [comment]
@bitinn Any update on this?
I've pushed a commit to detect if we should use InflateRaw according to the first byte (not aligned to browsers, hopefully it works :P).
Also, I think we should align to browsers' behaviour AMAP, so I think this workaround is necessary for us.

**Comment by bitinn** [comment]
@gzzhanghao I will keep this open for now, I would like to find a better solution then maintaining our own inflate lib (which is entirely a workaround).

**Comment by bitinn** [comment]
This is now fixed in v1.6.0, I chose a less verbose method, but still thank you very much for pointing me in the right direction.

**Pull request closed without merging**
