### PR TITLE
Added convenience methods .json() and .text() to the promise returned…

### PR DESCRIPTION
**Pull request by jrop**
Added convenience methods .json() and .text() to the promise returned by fetch()

This allows for (compacted) calls such as:

fetch('http://example/').text()
.then(theText => console.log(theText))

### CODE REVIEW

**Comment by jrop** [comment]
This PR references this issue: https://github.com/bitinn/node-fetch/issues/36

**Comment by bitinn** [comment]
I don't think #36 discussed this matter, it was in fact discussing `new Request()`, ie. using Request constructor directly, according to Fetch API https://fetch.spec.whatwg.org/ 

Likewise, you can write a helper library that wraps `node-fetch` to achieve the api shorthand you desire.

**Comment by olalonde** [comment]
:-1: this module should strictly follow the standard. Plus,

```javascript
fetch('http://example/').text()
.then(theText => console.log(theText))
```

 isn't that much better than

```javascript
fetch('http://example/').((r) => r.text())
.then(theText => console.log(theText))
```

**Comment by bitinn** [comment]
closing outdated PR

**Pull request closed without merging**
