### PR TITLE
Implement iterator on header

### PR DESCRIPTION
**Pull request by soyuka**
Node 6+ obviously

### CODE REVIEW

**Comment by TimothyGu** [comment]
Would it be easier if you implement `values`, `keys`, and `entries` with generator functions?

Either way, I don't think the current output of `values` and `keys` are quite correct, since they are missing a `next` function. With a generator function, you won't need to worry about such details.

Another question is if we should force the user to use Node.js v6+, or we should transpile the code using Babel.

**Comment by bitinn** [comment]
@TimothyGu would you like to be a contributor on this repo and drive this feature? I don't use ES6 feature that much so I haven't had time to investigate.

**Comment by bitinn** [comment]
@TimothyGu Oh and for the second question, my big concern is Node v4 LTS really. We can safely drop v0.10 and v0.12 by the end of this year (bump to `node-fetch` v2.0 of course).

**Comment by soyuka** [comment]
> Would it be easier if you implement values, keys, and entries with generator functions?

The result is the same IMO, but maybe it's cleaner using generators. I have a need to loop with `for (let v of)` on Headers, so I updated the polyfill without really thinking about the best implementation.

> Either way, I don't think the current output of values and keys are quite correct, since they are missing a next function. With a generator function, you won't need to worry about such details.

Yeah, I see what you say here, but nodejs wanted me to declare those on the `[Symbol.iterator]` key. By the way, tests are valid and pass, so IMO it's working as it should. Do you have another test in mind?

> Another question is if we should force the user to use Node.js v6+, or we should transpile the code using Babel.

Transpiling is a good idea IMO, babel would work for Iterators and Generator functions btw. 

> @TimothyGu Oh and for the second question, my big concern is Node v4 LTS really. We can safely drop v0.10 and v0.12 by the end of this year (bump to node-fetch v2.0 of course).

In pm2 we're waiting to drop the support for `v0.10` too... And yeah, the end of this year would be the period of choice. Anyway, to keep supporting node LTS we have to add transpiling. 

@TimothyGu let me know if you need some work on the es6/babel implementation

**Comment by TimothyGu** [comment]
@bitinn, yes please. I'll help whenever I can.

@soyuka,
>> Would it be easier if you implement values, keys, and entries with generator functions?
>
> The result is the same IMO, but maybe it's cleaner using generators. I have a need to loop with `for (let v of)` on Headers, so I updated the polyfill without really thinking about the best implementation.

Fair.

>> Either way, I don't think the current output of values and keys are quite correct, since they are missing a next function. With a generator function, you won't need to worry about such details.
>
> Yeah, I see what you say here, but nodejs wanted me to declare those on the `[Symbol.iterator]` key. By the way, tests are valid and pass, so IMO it's working as it should. Do you have another test in mind?

I see for `HeadersIterator` you've done it the right way: having a `next()` and a `@@iterator()` that returns `this`. It just should be the same case for `values` and `keys` as well.

**Comment by soyuka** [comment]
Ok, I'll improve this. Should I try including babel in this PR?

**Comment by TimothyGu** [comment]
No, don't worry about it. I have a PR incoming for that.

**Comment by bitinn** [comment]
@TimothyGu great you are now a collaborator.

So it looks like we do need a transpiler to get iterator working on Node v4. So be it :)

**Comment by soyuka** [comment]
Only node `0.10` doesn't pass. I had a `let` in the code which was breaking things, actually `0.12` seems to support iterators.

**Comment by jimmywarting** [comment]
https://www.npmjs.com/package/fetch-headers

**Comment by TimothyGu** [comment]
I've implemented #180, which incorporates elements of this pull request but also converts the entirety of Headers to ES2015. Please review.

**Pull request closed without merging**
