### PR TITLE
Make sure to finalize the request properly

### PR DESCRIPTION
**Pull request by TimothyGu**
Unfortunately, I could not write a test case that allows testing the bug
in #428.

Fixes: #428

### CODE REVIEW

**Comment by bitinn** [comment]
I used to use a trick where I set the timeout to be quite short and make sure the request is done before that, otherwise the test fail, does that approach work for testing this PR?

**Comment by bitinn** [comment]
I think I like your approach better as request is explicitly abort, but do make sure to credit @rzaharenkov for discovering this bug, it must have been there since one day of node-fetch?

**Comment by TimothyGu** [comment]
@bitinn The issue is more about the fact that I am so far unable to replicate the behavior of http://kjsubz.com in test/server.js. I'll keep digging.

**Comment by pjg** [comment]
Another URL we've had problems with was this redirection:
* http://tradeoptionswithme.com/ => https://tradeoptionswithme.com/

**Comment by TimothyGu** [comment]
I didn't end up finding a way to test this. Timeout don't work, because the socket timeout won't be triggered since it is not TTFB that's the issue; when the redirect is followed, the body timeout will refer to the redirected page.

The only way to test it would be executing a separate file and observing its behavior (specifically, its runtime). It is a fairly fragile approach however, and I feel it's too much complexity for this one change.

I'll get this merged, and then try to fix the code coverage issue (which came before this PR).

**Comment by pjg** [comment]
Hopefully you'll be able to cut a new release too for. Thanks!

**Comment by TimothyGu** [comment]
@pjg Published as v2.1.2.

**Comment by rzaharenkov** [comment]
I confirm that it solved our issue.

**Pull request merged**
